{
 "title": "my test app dash",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Namespace", "label": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  { "title": "API stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage by pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "CPU usage" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{namespace=~\"$Namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Scrape durations for pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "duration" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{pod=~\"prom-.*\",namespace=~\"$Namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Mem used by pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (app, pod, namespace)(jvm_memory_used_bytes{pod=~\"prom.*\", namespace=~\"$Namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}